# Generated by Django 5.2.8 on 2026-03-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='testimonials/videos/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
